# Generated by Django 3.1.7 on 2021-08-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210409_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_unit_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_unit_measure_fk', to='api.unitmeasures'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_unit_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_unit_measure_fk', to='api.unitmeasures'),
        ),
    ]
